# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: root # 用户名
    password: 123456  # 用户密码
server:
  port: 8761
eureka:
  client: #每个 eureka server 都有一个 eureka client,主要是同步 eureka server之间的元数据
    healthcheck:
      enabled: true
    register-with-eureka: false #指明不用将 eureka server 当作 eureka client 使用
    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka #http://localhost:8761/eureka #指明将 eureka 注册在哪个 url 上