zuul:
  routes:
    burst:
      path: /**
      url: microservice-provider-burst
    #user:
      #path: /**
      #url:  microservice-provider-user
    #poster:
      #path: /**
      #serviceId: microservice-provider-poster
    #courseware:
      #path: /**
      #serviceId: microservice-provider-courseware